export const MOCK_DATA = [
    {
        name: 'Тест команда',
        id: '56681',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 1,
    },
    {
        name: 'Стратегический комитет',
        id: '46963',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 9,
    },
    {
        name: 'Разработка Т11',
        id: '41103',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 5,
    },
    {
        name: 'Разработка Колесо Фортуны',
        id: '46856',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 8,
    },
    {
        name: 'Разработка Иврит',
        id: '52360',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 0,
    },
    {
        name: 'Разработка jira & jirahook',
        id: '53549',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 4,
    },
    {
        name: 'Разработка iOS Mostbet',
        id: '38703',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 11,
    },
    {
        name: 'Разработка YardHub',
        id: '40765',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 5,
    },
    {
        name: 'Разработка UmMoney',
        id: '50997',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 7,
    },
    {
        name: 'Разработка Traffic Cardinal',
        id: '41024',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 6,
    },
    {
        name: 'Разработка T9 (MST&BA)',
        id: '40825',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 7,
    },
    {
        name: 'Разработка T8 ',
        id: '40839',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 8,
    },
    {
        name: 'Разработка T6',
        id: '41146',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 6,
    },
    {
        name: 'Разработка T5 (Greenback)',
        id: '40824',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 13,
    },
    {
        name: 'Разработка T2 (Casino MST/BA)',
        id: '41228',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 8,
    },
    {
        name: 'Разработка T10 (Birpay)',
        id: '40831',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 10,
    },
    {
        name: 'Разработка T1 (Mostpartner)',
        id: '40586',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 14,
    },
    {
        name: 'Разработка T0',
        id: '41102',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 8,
    },
    {
        name: 'Разработка Switcherry VPN',
        id: '40758',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 9,
    },
    {
        name: 'Разработка Shakes&Cpagetti',
        id: '40652',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 9,
    },
    {
        name: 'Разработка Selfworker',
        id: '41023',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 10,
    },
    {
        name: 'Разработка Saptain',
        id: '41019',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 16,
    },
    {
        name: 'Разработка Portal Dats.Team',
        id: '40964',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 6,
    },
    {
        name: 'Разработка PDG Pay',
        id: '41207',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 10,
    },
    {
        name: 'Разработка P2P',
        id: '46846',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 7,
    },
    {
        name: 'Разработка Multicards',
        id: '40750',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 7,
    },
    {
        name: 'Разработка Mostbet.line',
        id: '40585',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 14,
    },
    {
        name: 'Разработка Mediabuying Tools',
        id: '40745',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 4,
    },
    {
        name: 'Разработка MWL iOS',
        id: '41074',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 13,
    },
    {
        name: 'Разработка MWL Sport',
        id: '41160',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 6,
    },
    {
        name: 'Разработка MWL Android ',
        id: '41079',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 12,
    },
    {
        name: 'Разработка MBC',
        id: '40730',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 10,
    },
    {
        name: 'Разработка Loyalty',
        id: '41167',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 11,
    },
    {
        name: 'Разработка Leadbit',
        id: '40650',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 10,
    },
    {
        name: 'Разработка Kinodostup',
        id: '52359',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 5,
    },
    {
        name: 'Разработка Ice Latte',
        id: '38657',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 5,
    },
    {
        name: 'Разработка Gamedev (Amarix)',
        id: '40713',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 14,
    },
    {
        name: 'Разработка Devbro',
        id: '52559',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 5,
    },
    {
        name: 'Разработка DTF',
        id: '40772',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 31,
    },
    {
        name: 'Разработка Billing',
        id: '38603',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 3,
    },
    {
        name: 'Разработка BPM/SQL-BI',
        id: '38622',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 9,
    },
    {
        name: 'Разработка Android Mostbet',
        id: '38428',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 13,
    },
    {
        name: 'Разработка AffiliateConf',
        id: '38550',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 5,
    },
    {
        name: 'Разработка Ads Report',
        id: '38426',
        avatar: '/upload/iblock/335/sqisxlzasg3nv23xszioc3726em7n5om/avatar.png',
        members: 7,
    },
    {
        name: 'Разработка AWL',
        id: '38582',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 11,
    },
    {
        name: 'Разработка 1С',
        id: '40662',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 11,
    },
    {
        name: 'Продуктовая команда Программа лояльности',
        id: '40625',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 3,
    },
    {
        name: 'Продуктовая команда Маркетинг',
        id: '40624',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 3,
    },
    {
        name: 'Продуктовая команда Колесо Фортуны',
        id: '40640',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 5,
    },
    {
        name: 'Продуктовая команда UmMoney',
        id: '50996',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 2,
    },
    {
        name: 'Продуктовая команда Sportbook',
        id: '40621',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 4,
    },
    {
        name: 'Продуктовая команда Payments (integration team)',
        id: '40626',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 5,
    },
    {
        name: 'Продуктовая команда PDG',
        id: '40628',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 4,
    },
    {
        name: 'Продуктовая команда P2P',
        id: '40639',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 5,
    },
    {
        name: 'Продуктовая команда Multicards',
        id: '51000',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 2,
    },
    {
        name: 'Продуктовая команда Mostpartner',
        id: '40642',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 5,
    },
    {
        name: 'Продуктовая команда Mostbet Mobile',
        id: '38429',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 7,
    },
    {
        name: 'Продуктовая команда Mostbet All',
        id: '40616',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 6,
    },
    {
        name: 'Продуктовая команда MWL Sport',
        id: '40636',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 4,
    },
    {
        name: 'Продуктовая команда MWL Loyalty',
        id: '40634',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 2,
    },
    {
        name: 'Продуктовая команда MWL Core',
        id: '38684',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 4,
    },
    {
        name: 'Продуктовая команда MWL Casino',
        id: '40963',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 3,
    },
    {
        name: 'Продуктовая команда MWL CMS',
        id: '40632',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 2,
    },
    {
        name: 'Продуктовая команда MBC',
        id: '40637',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 4,
    },
    {
        name: 'Продуктовая команда MBB',
        id: '40638',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 3,
    },
    {
        name: 'Продуктовая команда Lgaming',
        id: '40643',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 0,
    },
    {
        name: 'Продуктовая команда Greenback',
        id: '40627',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 3,
    },
    {
        name: 'Продуктовая команда Gamedev (Amarix)',
        id: '40641',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 5,
    },
    {
        name: 'Продуктовая команда DepHouse',
        id: '40644',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 0,
    },
    {
        name: 'Продуктовая команда Casino',
        id: '40633',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 4,
    },
    {
        name: 'Продуктовая команда Cashier',
        id: '40622',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 4,
    },
    {
        name: 'Продуктовая команда Birpay',
        id: '40629',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 3,
    },
    {
        name: 'Продуктовая команда Billing',
        id: '40630',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 6,
    },
    {
        name: 'Продуктовая команда Betandreas All',
        id: '40618',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 5,
    },
    {
        name: 'Продуктовая команда Banzai',
        id: '40645',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 0,
    },
    {
        name: 'Продуктовая команда BPM creatio',
        id: '38630',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 4,
    },
    {
        name: 'Продуктовая команда Antifraud',
        id: '40623',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 2,
    },
    {
        name: 'Продуктовая команда AWL',
        id: '38596',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 3,
    },
    {
        name: 'Подразделение Тестирования',
        id: '41121',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 13,
    },
    {
        name: 'Подразделение Support team',
        id: '41122',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 9,
    },
    {
        name: 'Подразделение DevOps',
        id: '38640',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 13,
    },
    {
        name: 'Подразделение Admins',
        id: '41134',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 10,
    },
    {
        name: 'Комитет UmMoney',
        id: '50995',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 0,
    },
    {
        name: 'Комитет Support Services',
        id: '38631',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 4,
    },
    {
        name: 'Комитет Services',
        id: '40665',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 4,
    },
    {
        name: 'Комитет Operations (payments)',
        id: '38611',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 3,
    },
    {
        name: 'Комитет Monolith brands',
        id: '38725',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 6,
    },
    {
        name: 'Комитет MWL ALL',
        id: '38689',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 5,
    },
    {
        name: 'Комитет GameDev',
        id: '40666',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 4,
    },
    {
        name: 'Комитет Affiliates',
        id: '40664',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 4,
    },
    {
        name: 'InfoSecurity',
        id: '55163',
        avatar: '/local/templates/it.codev.com/frontend/Adviva/dist/assets/avatar.png',
        members: 4,
    },
];
